// <auto-generated />
using System;
using CareerSphere.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareerSphere.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260214142539_add education and exp")]
    partial class addeducationandexp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CareerSphere.Models.ConnectionTableModel.Connection", b =>
                {
                    b.Property<Guid>("followerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("followingId")
                        .HasColumnType("char(36)");

                    b.HasKey("followerId", "followingId");

                    b.HasIndex("followingId");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("CareerSphere.Models.EducationTableModel.Education", b =>
                {
                    b.Property<Guid>("educationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("degree")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("userId")
                        .HasColumnType("char(36)");

                    b.HasKey("educationId");

                    b.HasIndex("userId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("CareerSphere.Models.EducationTableModel.Experience", b =>
                {
                    b.Property<Guid>("experienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("company")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("jobTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("userId")
                        .HasColumnType("char(36)");

                    b.HasKey("experienceId");

                    b.HasIndex("userId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("CareerSphere.Models.MessageTableModel.Conversation", b =>
                {
                    b.Property<Guid>("conversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("createdBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("lastmodifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("modifiedBy")
                        .HasColumnType("longtext");

                    b.Property<Guid>("userId")
                        .HasColumnType("char(36)");

                    b.HasKey("conversationId");

                    b.HasIndex("userId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("CareerSphere.Models.MessageTableModel.MessageModel", b =>
                {
                    b.Property<Guid>("messageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("conversationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("createdBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("lastmodifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("modifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("messageId");

                    b.HasIndex("conversationId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("CareerSphere.Models.PostTableModel.Post", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("contentImageUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("createdBy")
                        .HasColumnType("longtext");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("lastmodifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("modifiedBy")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("CareerSphere.Models.UserTableModel.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("about")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("createdBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("header")
                        .HasColumnType("longtext");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("lastmodifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("modifiedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("profileImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CareerSphere.Models.ConnectionTableModel.Connection", b =>
                {
                    b.HasOne("CareerSphere.Models.UserTableModel.User", "follower")
                        .WithMany("followings")
                        .HasForeignKey("followerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareerSphere.Models.UserTableModel.User", "following")
                        .WithMany("followers")
                        .HasForeignKey("followingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("follower");

                    b.Navigation("following");
                });

            modelBuilder.Entity("CareerSphere.Models.EducationTableModel.Education", b =>
                {
                    b.HasOne("CareerSphere.Models.UserTableModel.User", "user")
                        .WithMany("Educations")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("CareerSphere.Models.EducationTableModel.Experience", b =>
                {
                    b.HasOne("CareerSphere.Models.UserTableModel.User", "user")
                        .WithMany("Experiences")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("CareerSphere.Models.MessageTableModel.Conversation", b =>
                {
                    b.HasOne("CareerSphere.Models.UserTableModel.User", "User")
                        .WithMany("Conversations")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareerSphere.Models.MessageTableModel.MessageModel", b =>
                {
                    b.HasOne("CareerSphere.Models.MessageTableModel.Conversation", "conversation")
                        .WithMany("messages")
                        .HasForeignKey("conversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("conversation");
                });

            modelBuilder.Entity("CareerSphere.Models.PostTableModel.Post", b =>
                {
                    b.HasOne("CareerSphere.Models.UserTableModel.User", "user")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("CareerSphere.Models.MessageTableModel.Conversation", b =>
                {
                    b.Navigation("messages");
                });

            modelBuilder.Entity("CareerSphere.Models.UserTableModel.User", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("Posts");

                    b.Navigation("followers");

                    b.Navigation("followings");
                });
#pragma warning restore 612, 618
        }
    }
}
